---
apiVersion: v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
       app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: ankurpatel/nodejs_app:latest
        imagePullPolicy: Always
        resources:
            limits:
              memory: "2Gi"
              cpu: 2
            requests:
              memory: "1Gi"
              cpu: 1
        ports:
           - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name:  nodeapp
spec:
  selector:
    app:  nodeapp
  type:  NodePort
  ports:
  - name:  nodejsport
    port:  80
    targetPort:  8080
    nodePort: 30020
